# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: helm-unittest
        name: Helm-unittest
        files: ^charts/.*$
        entry: bin/pre-commit-hooks/helm-unittest.sh
        language: script
        pass_filenames: false
        always_run: true
      - id: helm-lint
        name: Helm-lint
        files: ^charts/.*$
        entry: bin/pre-commit-hooks/helm-lint.sh
        language: script
        pass_filenames: false
        always_run: true
