---
# Source: google-cloudrun-service/templates/manifest.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: 'minimal-service-stg'
  labels:
    cloud.googleapis.com/location: 'europe-west1'
    project: 'helmless'
    helmless-chart: 'google-cloudrun-service'
    helmless-chart-version: '0_1_0'
    managed-by: helmless
    env: 'stg'
  annotations:
    run.googleapis.com/launch-stage: 'BETA'
    run.googleapis.com/ingress: 'all'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/execution-environment: 'gen2'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/startup-cpu-boost: 'false'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: 'my-app-image'
          ports:
            - name: http1
              containerPort: 8080

          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 10

          resources:
            limits:
              cpu: '1'
              memory: '512Mi'
