{{- include "helmless.cloudrun.validateCPU" . }}
{{- include "helmless.cloudrun.validateVolumes" . }}
apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: {{ .Values.name | quote }}
  labels:
    cloud.googleapis.com/location: {{ include "helmless.cloudrun.region" . | quote }}
  annotations:
    run.googleapis.com/launch-stage: {{ .Values.launchStage | default "BETA" | quote }}
    {{- if .Values.binaryAuthorization }}
    run.googleapis.com/binary-authorization: "default"
    {{- end }}
spec:
  template:
    metadata:
      {{- if .Values.revisionName }}
      name: {{ printf "%s-%s" .Values.name .Values.revisionName | quote }}
      {{- end }}
      annotations:
        {{- with include "helmless.cloudrun.cloudsql" . }}
        run.googleapis.com/cloudsql-instances: {{ . }}
        {{- end }}
        {{- if .Values.network }}
        {{- with .Values.network.connector }}
        run.googleapis.com/vpc-access-connector: {{ . | quote }}
        {{- end }}
        run.googleapis.com/vpc-access-egress: {{ .Values.network.egress | default "private-ranges-only" | quote }}
        {{- if and .Values.network.vpc .Values.network.subnetwork }}
        run.googleapis.com/network-interfaces: {{ include "helmless.cloudrun.networkInterfaces" .Values.network | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.encryption }}
        run.googleapis.com/encryption-key: {{ printf "projects/%s/locations/%s/keyRings/%s/cryptoKeys/%s" .Values.project (include "helmless.cloudrun.region" .) .Values.encryption.keyring .Values.encryption.key | quote }}
        {{- end }}
    spec:
      parallelism: PARALLELISM
      taskCount: TASK_COUNT
      template:
        spec:
          maxRetries: MAX_RETRIES
          timeoutSeconds: TASK_TIMEOUT
          {{- with .Values.serviceAccountName }}
          serviceAccountName: {{ . }}
          {{- end }}
          containers:
          - image: {{ include "helmless.cloudrun.image" . | quote }}
            {{- with .Values.containerName }}
            name: {{ . | quote }}
            {{- end }}
            {{- with .Values.command }}
            command:
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.args }}
            args:
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if or .Values.env .Values.secrets .Values.cloudsql }}
            env: {{- include "helmless.cloudrun.env" . | nindent 10 }}
            {{- end }}
            resources:
              limits:
                cpu: {{ ((.Values.resources).limits).cpu | default 1 | quote }}
                memory: {{ ((.Values.resources).limits).memory | default "512Mi" | quote }}
            {{- with .Values.volumes }}
            volumeMounts:
              {{- range $name, $volume := . }}
              - name: {{ $name | quote }}
                mountPath: {{ $volume.mountPath | quote }}
                readOnly: {{ $volume.readOnly | default false }}
              {{- end }}
            {{- end }}
          {{- with .Values.volumes }}
          volumes: {{- include "helmless.cloudrun.volumes" . | nindent 10 }}
          {{- end }}
