name: sql-vpc-service
region: europe-west1
project: helmless
image: gcr.io/helmless/hello-world:latest
network:
  vpc: projects/helmless/global/networks/default
  subnetwork: projects/helmless/regions/europe-west1/subnetworks/default
  egress: private-ranges-only
cloudsql:
  instance: main
  project: helmless
  region: europe-west1
