apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.name | quote }}
  labels:
    cloud.googleapis.com/location: {{ .Values.region | default "us-central1" | quote }}
  annotations:
    {{- with .Values.description }}
    run.googleapis.com/description: {{ . | quote }}
    {{- end }}
    run.googleapis.com/launch-stage: {{ .Values.launchStage | default "BETA" | quote }}
    {{- if .Values.binaryAuthorization }}
    run.googleapis.com/binary-authorization: "true"
    {{- end }}
    {{- if .Values.disableInvokerIamPolicy }}
    run.googleapis.com/invoker-iam-disabled: "true"
    {{- end }}
    run.googleapis.com/ingress: INGRESS
    run.googleapis.com/binary-authorization-breakglass: JUSTIFICATION
    run.googleapis.com/minScale: SERVICE_MIN_INSTANCES
    run.googleapis.com/function-target: FUNCTION_ENTRY_POINT
spec:
  template:
    metadata:
      {{- with .Values.revisionName }}
      name: {{ . | quote }}
      {{- end }}
      annotations:
        {{- with .Values.encryptionKey }}
        run.googleapis.com/encryption-key: {{ . | quote }}
        {{- end }}
        {{- with .Values.customAudiences }}
        run.googleapis.com/custom-audiences: {{ . | toJson | quote }}
        {{- end }}
        autoscaling.knative.dev/minScale: MIN_INSTANCES
        autoscaling.knative.dev/maxScale: MAX_INSTANCES
        run.googleapis.com/cpu-throttling: CPU_ALLOCATION
        run.googleapis.com/startup-cpu-boost: CPU_BOOST
        run.googleapis.com/sessionAffinity: SESSION_AFFINITY
        run.googleapis.com/cloudsql-instances: CLOUD_SQL_CONNECTION
        run.googleapis.com/execution-environment: {{ .Values.executionEnvironment | default "gen2" }}
        run.googleapis.com/vpc-access-connector: SERVERLESS_VPC_CONNECTOR
        run.googleapis.com/vpc-access-egress: EGRESS
        run.googleapis.com/network-interfaces: VPC_NETWORK_SETTINGS_IN_JSON
        run.googleapis.com/container-dependencies: CONTAINER_START_ORDER
        run.googleapis.com/base-images: '{"":"BASE_IMAGE"}'
    spec:
      {{- with .Values.serviceAccountName }}
      serviceAccountName: {{ . }}
      {{- end }}
      containerConcurrency: MAX_CONCURRENCY
      timeoutSeconds: REQUEST_TIMEOUT
      nodeSelector:
        run.googleapis.com/accelerator: GPU_TYPE
      containers:
        - image: {{ include "helmless.image" . | quote }}
          {{- with .Values.containerName }}
          name: {{ . | quote }}
          {{- end }}
          {{- with .Values.command }}
          command:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ .Values.http2 | default false | ternary "h2c" "http1" }}
              containerPort: {{ .Values.containerPort | default 8080 }}
          env:
            - name: KEY
              value: VALUE
          resources:
            limits:
              cpu: CPU_LIMIT
              memory: MEMORY_LIMIT
              nvidia.com/gpu: GPU_NUMBER
          volumeMounts:
            - name: VOLUME_NAME
              mountPath: MOUNT_PATH
          startupProbe:
            httpGet:
              path: CHECK_PATH
              httpHeaders:
                - name: HEADER_NAME
                  value: HEADER_VALUE
              port: PORT
            tcpSocket:
              port: PORT
            grpc:
              service: GRPC_SERVICE
              port: PORT
            initialDelaySeconds: DELAY
            timeoutSeconds: TIMEOUT
            failureThreshold: THRESHOLD
            periodSeconds: PERIOD
          livenessProbe:
            httpGet:
              path: CHECK_PATH
              port: PORT
              httpHeaders:
                - name: HEADER_NAME
                  value: HEADER_VALUE
            grpc:
              service: GRPC_SERVICE
              port: PORT
            initialDelaySeconds: DELAY
            timeoutSeconds: TIMEOUT
            failureThreshold: THRESHOLD
            periodSeconds: PERIOD
        - image: SIDECAR_IMAGE
          name: SIDECAR_NAME
      volumes:
        - name: VOLUME_NAME
          secret:
            secretName: SECRET
            items:
              - key: SECRET_VERSION
                path: PATH
        - name: VOLUME_NAME
          emptyDir:
            sizeLimit: IN_MEMORY_VOLUME_SIZE
            medium: Memory
        - name: VOLUME_NAME
          csi:
            driver: gcsfuse.run.googleapis.com
            readOnly: IS_READ_ONLY
            volumeAttributes:
              bucketName: BUCKET_NAME
              mountOptions: OPTION1-NAME=OPTION1-VALUE,OPTION2-NAME=OPTION2-VALUE
        - name: VOLUME_NAME
          nfs:
            server: IP_ADDRESS
            path: NFS_PATH
            readonly: IS_READ_ONLY
    runtimeClassName: RUNTIME
  traffic:
    - percent: PERCENT_TO_LATEST
      latestRevision: true
    - percent: PERCENT_TO_REVISION
      revisionName: REVISION_NAME
    - tag: TAG
      revisionName: REVISION_NAME
