name: 🚀 Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release:
    name: 🏷️ Release Please
    runs-on: ubuntu-22.04
    outputs:
      paths_released: ${{ steps.release.outputs.paths_released }}
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      # Required so that a release triggers follow up workflows
      - name: 🔑 Generate Token
        id: generate-token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ secrets.CI_BOT_ID }}
          application_private_key: ${{ secrets.CI_BOT_KEY }}

      - name: 📦 Create Release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ steps.generate-token.outputs.token }}

  publish:
    name: 📦 Publish Helm Chart ${{ matrix.path }}
    runs-on: ubuntu-22.04
    needs: release
    if: ${{ needs.release.outputs.releases_created && needs.release.outputs.paths_released != '' && needs.release.outputs.paths_released != '[]' }}
    strategy:
      matrix:
        path: ${{ fromJson(needs.release.outputs.paths_released) }}
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: ⚙️ Install Helm
        uses: azure/setup-helm@v4

      - name: 📦 Package Helm Chart
        run: |
          helm package --dependency-update ${{ matrix.path }}

      - name: 🔐 Set up OCI Registry Authentication
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: 🐳 Push to GitHub Container Registry
        run: |
          helm push *.tgz oci://ghcr.io/${{ github.repository_owner }}
